// AUTO-GENERATED by backend/scripts/templatize-library.ts — do not edit by hand.
// Maps a prompt slug to the typed variable fields ([TOKEN] placeholders) in its descriptive layer.
import type { VariableField } from "./api";

export const promptVariables: Record<string, VariableField[]> = {
  "MKT-ADC-001": [
    {
      "name": "PRODUCT",
      "label": "Product",
      "type": "image",
      "placeholder": "e.g. running sneakers"
    }
  ]
};
