export interface WebsiteDesign {
  id: string; slug: string; title: string; subtitle: string;
  category: string; subCategory: string; style: string;
  description: string; stack: string[]; screenshot: string;
  rating: number; tested: boolean; tags: string[];
  accentColor: string; bgColor: string;
}

export const websiteDesigns: WebsiteDesign[] = [
  {
    id: "business_01", slug: "business_01",
    title: "Results-Led Trust", subtitle: "Competitive Exam Coaching Institute",
    category: "Business Website", subCategory: "Educational Institute / Coaching Centre",
    style: "IIT-JEE / NEET Coaching Website",
    description: "This is a business website for a top Indian coaching institute preparing students for IIT-JEE, NEET-UG, Olympiads, and foundation programs. The platform must convert high-intent traffic into counselin...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["education", "institute"],
    accentColor: "#1565C0", bgColor: "#F0F4FF",
  },
  {
    id: "business_02", slug: "business_02",
    title: "Scale + Trust", subtitle: "Mass-Market Indian Coaching Brand Website",
    category: "Business Website", subCategory: "Educational Institute / Coaching Centre",
    style: "Multi-Program Coaching Admissions Platform",
    description: "This is a business website for a mass-market coaching brand preparing students for JEE, NEET, Foundation, Olympiads, and school-support pathways across multiple learning modes (classroom, digital, dis...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["education", "institute"],
    accentColor: "#1565C0", bgColor: "#F0F4FF",
  },
  {
    id: "business_03", slug: "business_03",
    title: "Personalized Outcomes", subtitle: "Premium EdTech K-12 and Competitive Preparation Platform",
    category: "Business Website", subCategory: "Educational Institute / Coaching Centre",
    style: "K-12 and Competitive Learning Platform",
    description: "This is a premium edtech platform serving K-12 students and competitive exam aspirants. The product portfolio includes personalized learning apps, online tutoring, JEE/NEET preparation, foundational s...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["education", "institute"],
    accentColor: "#1565C0", bgColor: "#F0F4FF",
  },
  {
    id: "business_04", slug: "business_04",
    title: "Placement Guarantee", subtitle: "Career Acceleration & Tech Upskilling Platform",
    category: "Business Website", subCategory: "Educational Institute / Coaching Centre",
    style: "Career Acceleration & Tech Upskilling Platform",
    description: "This is a premium edtech platform serving K-12 students and competitive exam aspirants. The product portfolio includes personalized learning apps, online tutoring, JEE/NEET preparation, foundation sch...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["education", "institute"],
    accentColor: "#1565C0", bgColor: "#F0F4FF",
  },
  {
    id: "bw_01", slug: "bw_01",
    title: "HeritageLuxury", subtitle: "Premium Indian Designer Wear",
    category: "Business Website", subCategory: "Boutique / Retail Store",
    style: "Artisanal Storytelling & Modern Fashion",
    description: "This is a premium digital storefront and heritage hub for a leading global Indian fashion house. The audience consists of high-net-worth brides, luxury fashion enthusiasts, and conscious consumers int...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#1A1A1A", bgColor: "#FAFAF8",
  },
  {
    id: "bw_02", slug: "bw_02",
    title: "DramaticLuxury", subtitle: "Iconic Indian Luxury Brand",
    category: "Business Website", subCategory: "Boutique / Retail Store",
    style: "Restrained Opulence & Visual Poetry",
    description: "This is an iconic digital flagship for a world-renowned Indian luxury brand. The audience consists of global high-net-worth individuals, museum curators, and fashion historians. The goal is to provide...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#1A1A1A", bgColor: "#FAFAF8",
  },
  {
    id: "bw_03", slug: "bw_03",
    title: "SutaStyle", subtitle: "Modern Indian D2C Boutique",
    category: "Business Website", subCategory: "Boutique / Retail Store",
    style: "Homely Modern & Story-Led Commerce",
    description: "This is a high-performance digital storefront and community hub for a leading Indian D2C saree and lifestyle brand. The audience consists of modern women seeking \"Everyday Elegance,\" ethical consumers...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#1A1A1A", bgColor: "#FAFAF8",
  },
  {
    id: "bw_04", slug: "bw_04",
    title: "TropicalMinimalist", subtitle: "Indian Lifestyle Retail",
    category: "Business Website", subCategory: "Boutique / Retail Store",
    style: "Content-Led Retail & Modern Indian Utility",
    description: "This is a premium digital flagship and lifestyle hub for a leading modern Indian retail brand. The audience consists of \"Modern Nomads\"-creative professionals who value high-quality materials, breezy ...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#1A1A1A", bgColor: "#FAFAF8",
  },
  {
    id: "bw_05", slug: "bw_05",
    title: "CulinaryNarrative", subtitle: "Best-in-class Indian Restaurant",
    category: "Business Website", subCategory: "Restaurant / Cafe",
    style: "Art-Deco Sophistication & Glocal Dining",
    description: "This is a premium digital flagship for a world-renowned modern Indian restaurant. The audience consists of local food enthusiasts, international travelers, and event planners. The goal is to provide a...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#067A46", bgColor: "#FFFDF6",
  },
  {
    id: "bw_06", slug: "bw_06",
    title: "CoastalJoy", subtitle: "Modern Indian Restaurant Brand",
    category: "Business Website", subCategory: "Restaurant / Cafe",
    style: "Tropical Portuguese-Goan Hospitality",
    description: "This is a premium digital hub for an award-winning modern Indian restaurant that reimagines Portuguese-Goan cuisine. The audience consists of Mumbai cosmopolitans, luxury travelers, and culinary explo...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#067A46", bgColor: "#FFFDF6",
  },
  {
    id: "bw_07", slug: "bw_07",
    title: "PrestigeMinimalism", subtitle: "Global Fine-Dining Restaurant",
    category: "Business Website", subCategory: "Restaurant / Cafe",
    style: "Architectural Clarity & Inventive Dining",
    description: "This is a premium digital flagship for an internationally acclaimed progressive Indian restaurant group. The audience consists of global travelers, culinary connoisseurs, and corporate hosts. The goal...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#067A46", bgColor: "#FFFDF6",
  },
  {
    id: "bw_clinic_01", slug: "bw_clinic_01",
    title: "Large Indian Hospital Network", subtitle: "Apollo Hospitals",
    category: "Business Website", subCategory: "Doctor / Clinic / Hospital",
    style: "Large Indian Hospital Network",
    description: "Brand Voice & Mood: Authoritative clinical competence with approachable warmth - teal 2582A1 conveys medical professionalism; gold FDB931 adds warmth to star ratings and accreditation highlights. The ...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#2582A1", bgColor: "#F0F7FA",
  },
  {
    id: "bw_clinic_02", slug: "bw_clinic_02",
    title: "Doctor Discovery + Booking Platform", subtitle: "Practo",
    category: "Business Website", subCategory: "Doctor / Clinic / Hospital",
    style: "Doctor Discovery + Booking Platform",
    description: "Brand Voice & Mood: Consumer-digital, direct, high-density - cyan 14BEF0 is energetic and action-forward; navy 28328C anchors authority. The design language is flat: 4px border-radius everywhere (butt...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#2582A1", bgColor: "#F0F7FA",
  },
  {
    id: "bw_clinic_03", slug: "bw_clinic_03",
    title: "Global Hospital Authority Portal", subtitle: "Cleveland Clinic (my.clevelandclinic.org)",
    category: "Business Website", subCategory: "Doctor / Clinic / Hospital",
    style: "Global Hospital Authority Portal",
    description: "Brand Voice & Mood: Institutional authority through data - the design conveys excellence via metrics (35,000+ heart procedures, 1 US News ranking) rather than marketing copy. Blue 0468CD is the action...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#2582A1", bgColor: "#F0F7FA",
  },
  {
    id: "bw_clinic_04", slug: "bw_clinic_04",
    title: "Modern Indian Diagnostic Marketplace", subtitle: "Cult.fit Care (cult.fit/care)",
    category: "Business Website", subCategory: "Doctor / Clinic / Hospital",
    style: "Modern Indian Diagnostic Marketplace",
    description: "Brand Voice & Mood: Bold and e-commerce-driven - dark 15171C backgrounds signal premium health tech; pink FF316D creates urgency for discounted packages. The Aurora glassmorphism cards (backdrop-filte...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#2582A1", bgColor: "#F0F7FA",
  },
  {
    id: "bw_legal_01", slug: "bw_legal_01",
    title: "Premier Indian Law Firm", subtitle: "Cyril Amarchand Mangaldas",
    category: "Business Website", subCategory: "Lawyer / CA / Consulting",
    style: "Premier Indian Law Firm",
    description: "Role: Senior brand designer and visual strategist specialising in prestige Indian law firm websites, institutional authority positioning, and serif/sans-serif typographic identity systems.",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#4B2E6B", bgColor: "#FAFAF9",
  },
  {
    id: "bw_legal_02", slug: "bw_legal_02",
    title: "Top-Tier Indian Law Firm", subtitle: "AZB & Partners",
    category: "Business Website", subCategory: "Lawyer / CA / Consulting",
    style: "Top-Tier Indian Law Firm",
    description: "Role: Senior product designer specialising in top-tier Indian law firm websites, scroll-triggered architectural design systems, and tabbed hero narrative patterns.",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#4B2E6B", bgColor: "#FAFAF9",
  },
  {
    id: "bw_legal_03", slug: "bw_legal_03",
    title: "Indian CA / Tax Filing Service", subtitle: "ClearTax",
    category: "Business Website", subCategory: "Lawyer / CA / Consulting",
    style: "Indian CA / Tax Filing Service",
    description: "Role: Senior product designer specialising in Indian fintech and professional services platforms, dark-first consumer UX, and dual-path self-serve vs. expert-assist conversion flows.",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#4B2E6B", bgColor: "#FAFAF9",
  },
  {
    id: "bw_legal_04", slug: "bw_legal_04",
    title: "Indian Legal Services Platform (Productized)", subtitle: "Vakilsearch",
    category: "Business Website", subCategory: "Lawyer / CA / Consulting",
    style: "Indian Legal Services Platform (Productized)",
    description: "Brand Voice & Mood: Consumer e-commerce confidence applied to legal services - transparent, outcome-driven, trust-heavy. Navy 022B50 signals authority; yellow FFD000 signals speed, savings, and action...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#4B2E6B", bgColor: "#FAFAF9",
  },
  {
    id: "bw_realestate_01", slug: "bw_realestate_01",
    title: "Indian Property Listing Portal", subtitle: "MagicBricks (magicbricks.com)",
    category: "Business Website", subCategory: "Real Estate / Property Listing",
    style: "Indian Property Listing Portal",
    description: "Brand Voice & Mood: Practical and information-dense - red E03228 signals urgency and action; the neutral surface palette (F4F5F7, 2D2D2D, 717171) keeps property data legible. Indian real estate pricin...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#E53935", bgColor: "#F5F5F5",
  },
  {
    id: "bw_realestate_02", slug: "bw_realestate_02",
    title: "Indian Property Detail Page", subtitle: "Indian Property Detail Page",
    category: "Business Website", subCategory: "Real Estate / Property Listing",
    style: "Indian Property Detail Page",
    description: "Brand Voice & Mood: Trust-forward and informative - orange E84118 signals energy and urgency (price callouts, CTAs, active states), while the surface palette (F5F5F5 bg, 212121 text, 666666 muted) kee...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#E53935", bgColor: "#F5F5F5",
  },
  {
    id: "bw_realestate_03", slug: "bw_realestate_03",
    title: "Indian Premium Property Portal", subtitle: "Indian Premium Property Portal",
    category: "Business Website", subCategory: "Real Estate / Property Listing",
    style: "Indian Premium Property Portal",
    description: "Brand Voice & Mood: Premium and investment-forward - teal 0B6E77 signals authority and trust; gold C9941A signals premium yield and high-value properties. The portal speaks to serious buyers and NRI i...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#E53935", bgColor: "#F5F5F5",
  },
  {
    id: "bw_realestate_04", slug: "bw_realestate_04",
    title: "Modern Indian Rental Discovery", subtitle: "Modern Indian Rental Discovery",
    category: "Business Website", subCategory: "Real Estate / Property Listing",
    style: "Modern Indian Rental Discovery",
    description: "Brand Voice & Mood: Empowering and direct - purple 6C3CE1 signals a modern challenger brand disrupting traditional brokerage. Green 15803D is exclusively for zero-brokerage messaging, savings amounts,...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#E53935", bgColor: "#F5F5F5",
  },
  {
    id: "bw_service_01", slug: "bw_service_01",
    title: "Indian Email Marketing SaaS Landing Page", subtitle: "Indian Email Marketing SaaS Landing Page",
    category: "Landing Pages", subCategory: "SaaS / Software Product",
    style: "Indian Email Marketing SaaS Landing Page",
    description: "MailFlow is an Indian email marketing and automation SaaS platform targeting Indian SMBs, D2C e-commerce brands, and growing startups. Visitors arrive researching tools or switching from generic platf...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#6366F1", bgColor: "#0F0F23",
  },
  {
    id: "bw_service_02", slug: "bw_service_02",
    title: "Indian Web Agency Directory", subtitle: "Indian Web Agency Directory",
    category: "Landing Pages", subCategory: "SaaS / Software Product",
    style: "Indian Web Agency Directory",
    description: "AgencyHub is an Indian web design and development agency directory - a curated marketplace connecting Indian businesses with verified digital agencies. Visitors are business owners, marketing managers...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#6366F1", bgColor: "#0F0F23",
  },
  {
    id: "bw_service_03", slug: "bw_service_03",
    title: "Indian Payment Gateway Service Page", subtitle: "Indian Payment Gateway Service Page",
    category: "Landing Pages", subCategory: "SaaS / Software Product",
    style: "Indian Payment Gateway Service Page",
    description: "PayFlow is an Indian payment gateway SaaS platform targeting Indian SMBs, D2C e-commerce stores, and tech startups integrating payments. Visitors are developers evaluating APIs or business owners comp...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#6366F1", bgColor: "#0F0F23",
  },
  {
    id: "bw_service_04", slug: "bw_service_04",
    title: "Indian Stock Broker Service Page", subtitle: "Indian Stock Broker Service Page",
    category: "Landing Pages", subCategory: "SaaS / Software Product",
    style: "Indian Stock Broker Service Page",
    description: "ZeroTrade is an Indian discount stockbroker platform communicating a single USP: ₹0 brokerage on equity delivery, ₹20 flat on everything else. Visitors are traders and investors comparing brokers or e...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["business", "website"],
    accentColor: "#6366F1", bgColor: "#0F0F23",
  },
  {
    id: "dpecom_01", slug: "dpecom_01",
    title: "Neo-Creator", subtitle: "Creator Digital Storefront",
    category: "E-Commerce", subCategory: "Digital Product Store",
    style: "Bold Digital Goods Marketplace",
    description: "This is a digital storefront for creators to sell products (PDFs, videos, software, memberships). The customer is a \"knowledge seeker\" or \"fan\" who values direct support and immediate access. The crea...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["digital", "store"],
    accentColor: "#7C3AED", bgColor: "#0F0F1A",
  },
  {
    id: "dpecom_02", slug: "dpecom_02",
    title: "Squeezed", subtitle: "SaaS & Software Storefront",
    category: "E-Commerce", subCategory: "Digital Product Store",
    style: "Polished Digital Commerce & Subscriptions",
    description: "This is an all-in-one platform for software creators to sell digital downloads, SaaS subscriptions, and license keys. The customer is a professional or business user looking for a reliable tool. The c...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["digital", "store"],
    accentColor: "#7C3AED", bgColor: "#0F0F1A",
  },
  {
    id: "dpecom_03", slug: "dpecom_03",
    title: "Kit-Style", subtitle: "Audience-First Creator Storefront",
    category: "E-Commerce", subCategory: "Digital Product Store",
    style: "Clean Creative Commerce & Newsletters",
    description: "This is an integrated commerce and email-marketing platform for creators. The customer is a \"superfan\" or \"subscriber\" looking to support their favorite creator. The creator is a writer, artist, or ed...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["digital", "store"],
    accentColor: "#7C3AED", bgColor: "#0F0F1A",
  },
  {
    id: "dpecom_04", slug: "dpecom_04",
    title: "Top-Tier", subtitle: "Creator Service Storefront",
    category: "E-Commerce", subCategory: "Digital Product Store",
    style: "Professional Creator Service Platform",
    description: "This is a personal storefront platform for creators to monetize their expertise through 1:1 sessions, webinars, digital products, and priority DMs. The customer is a \"mentee\" or \"follower\" seeking dir...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["digital", "store"],
    accentColor: "#7C3AED", bgColor: "#0F0F1A",
  },
  {
    id: "ecomm_01", slug: "ecomm_01",
    title: "Natural Comfort", subtitle: "Fashion D2C Storefront",
    category: "E-Commerce", subCategory: "Single Product (Shopify-style)",
    style: "Sustainable Fashion Storefront",
    description: "This is a direct-to-consumer e-commerce storefront for a sustainable footwear and apparel brand. The customer is an adult aged 25–45 who cares about what their purchases are made from, values comfort ...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["ecommerce", "product"],
    accentColor: "#16A34A", bgColor: "#FFFFFF",
  },
  {
    id: "ecomm_02", slug: "ecomm_02",
    title: "Nothing To Hide", subtitle: "Health Food D2C Storefront",
    category: "E-Commerce", subCategory: "Single Product (Shopify-style)",
    style: "Clean Ingredient Food Brand",
    description: "This is a direct-to-consumer e-commerce storefront for a clean-ingredient food brand. The brand sells protein bars, protein powders, and healthy snacks made with declared, recognisable ingredients - n...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["ecommerce", "product"],
    accentColor: "#16A34A", bgColor: "#FFFFFF",
  },
  {
    id: "ecomm_03", slug: "ecomm_03",
    title: "Better-For-You Soda", subtitle: "Functional Beverage D2C Storefront",
    category: "E-Commerce", subCategory: "Single Product (Shopify-style)",
    style: "Flavor-First Functional Beverage Storefront",
    description: "This is a direct-to-consumer storefront for a better-for-you soda brand. The products are canned beverages positioned as delicious soda alternatives with functional benefits such as fiber and gut-frie...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["ecommerce", "product"],
    accentColor: "#16A34A", bgColor: "#FFFFFF",
  },
  {
    id: "lp_01", slug: "lp_01",
    title: "EventImpact", subtitle: "Global Scale Multi-Day Conference",
    category: "Landing Pages", subCategory: "Event / Conference",
    style: "High-Energy Cinematic Landing & Ticketing",
    description: "This is a premium digital hub for a global multi-day tech conference. The audience consists of startup founders, venture capitalists, corporate executives, and international media. The goal is to prov...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["landing-page"],
    accentColor: "#E31E24", bgColor: "#0A0A0A",
  },
  {
    id: "lp_02", slug: "lp_02",
    title: "LeaderShip-X", subtitle: "Enterprise Tech Summit & Leadership Forum",
    category: "Landing Pages", subCategory: "Event / Conference",
    style: "Authoritative Corporate Events & Industry Themes",
    description: "This is a premium digital hub for a leading technology and leadership forum in Asia. The audience consists of C-level executives, policy makers, startup founders, and industry analysts. The goal is to...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["landing-page"],
    accentColor: "#E31E24", bgColor: "#0A0A0A",
  },
  {
    id: "lp_03", slug: "lp_03",
    title: "LumaStyle", subtitle: "Social-First Event Landing Page",
    category: "Landing Pages", subCategory: "Event / Conference",
    style: "Elegant Invitations & Community Discovery",
    description: "This is a premium digital hub for creating and discovering high-quality events and communities. The audience consists of creative professionals, tech innovators, and community organizers. The goal is ...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["landing-page"],
    accentColor: "#E31E24", bgColor: "#0A0A0A",
  },
  {
    id: "lp_04", slug: "lp_04",
    title: "ZenContent", subtitle: "Minimal Personal Brand & Content Archive",
    category: "Landing Pages", subCategory: "Personal Brand / Creator",
    style: "Extreme Minimalism & Timeless Wisdom",
    description: "This is a premium digital archive for a world-renowned thinker and entrepreneur. The audience consists of lifelong learners, founders, and seekers of timeless wisdom. The goal is to provide a \"Digital...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["landing-page"],
    accentColor: "#094067", bgColor: "#FFFFFF",
  },
  {
    id: "lp_05", slug: "lp_05",
    title: "AuthorityArchive", subtitle: "High-Authority Creator Brand & Monetization Hub",
    category: "Landing Pages", subCategory: "Personal Brand / Creator",
    style: "Content Ecosystem & Multi-Channel Monetization",
    description: "This is a premium digital hub for a world-class creator, author, and podcast host. The audience consists of high-performing professionals, entrepreneurs, and seekers of \"Tactics and Tools.\" The goal i...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["landing-page"],
    accentColor: "#094067", bgColor: "#FFFFFF",
  },
  {
    id: "lp_06", slug: "lp_06",
    title: "CreatorEcosystem", subtitle: "Multi-Product Creator Business & Hub",
    category: "Landing Pages", subCategory: "Personal Brand / Creator",
    style: "Modular Discovery & Feel-Good Branding",
    description: "This is a premium digital flagship for a world-class creator-entrepreneur. The audience consists of students, founders, and professionals seeking \"Sustainable Success.\" The goal is to provide a \"Singl...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["landing-page"],
    accentColor: "#094067", bgColor: "#FFFFFF",
  },
  {
    id: "lp_07", slug: "lp_07",
    title: "WarikooStyle", subtitle: "Indian Creator Hub & Multi-Product Portfolio",
    category: "Landing Pages", subCategory: "Personal Brand / Creator",
    style: "Radical Transparency & Personal Authority",
    description: "This is a premium digital hub for a leading Indian entrepreneur, author, and educator. The audience consists of millions of students, professionals, and aspiring creators seeking \"Real-World Skills\" (...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["landing-page"],
    accentColor: "#094067", bgColor: "#FFFFFF",
  },
  {
    id: "lp_08", slug: "lp_08",
    title: "StudioQuiet", subtitle: "Single-Input Waitlist & Minimalist Teaser",
    category: "Landing Pages", subCategory: "SaaS / Software Product",
    style: "Single-Input Hype & Studio Minimalism",
    description: "This is a premium minimalist \"Teaser\" page for an upcoming creative social network or tool. The audience consists of designers, developers, and high-end creative \"Operators.\" The goal is to provide a ...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["landing-page"],
    accentColor: "#6366F1", bgColor: "#0F0F23",
  },
  {
    id: "lp_09", slug: "lp_09",
    title: "PyramidVelocity", subtitle: "One-Screen Value Prop & Beta Social Proof",
    category: "Landing Pages", subCategory: "SaaS / Software Product",
    style: "Inverted Hierarchy & Early-Access Proof",
    description: "This is a premium one-screen landing page for a cutting-edge digital tool (e.g., Email, AI, or SaaS). The audience consists of \"Power Users\" and early adopters seeking high-efficiency solutions. The g...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["landing-page"],
    accentColor: "#6366F1", bgColor: "#0F0F23",
  },
  {
    id: "lp_10", slug: "lp_10",
    title: "TallySimplicity", subtitle: "Product Waitlist & Form-Builder Teaser",
    category: "Landing Pages", subCategory: "SaaS / Software Product",
    style: "Notion-Native Productivity & Action-First Waitlists",
    description: "This is a premium product landing hub for a next-generation form builder or productivity tool. The audience consists of digital solopreneurs, product managers, and creative operators. The goal is to p...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["landing-page"],
    accentColor: "#6366F1", bgColor: "#0F0F23",
  },
  {
    id: "lp_11", slug: "lp_11",
    title: "GalleryElite", subtitle: "Template Gallery & Marketplace Hub",
    category: "Landing Pages", subCategory: "SaaS / Software Product",
    style: "Visual Curation & Remix-to-Convert Discovery",
    description: "This is a premium digital hub for discovering and cloning high-quality web templates. The audience consists of designers, developers, and founders seeking \"Instant Quality.\" The goal is to provide a \"...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["landing-page"],
    accentColor: "#6366F1", bgColor: "#0F0F23",
  },
  {
    id: "lp_12", slug: "lp_12",
    title: "CinematicStory", subtitle: "Product Showcase & Cinematic Scrollytelling",
    category: "Landing Pages", subCategory: "SaaS / Software Product",
    style: "Motion-Driven Discovery & High-Fidelity Specs",
    description: "This is a premium digital flagship for a high-end consumer technology product (e.g., AirPods). The audience consists of design-conscious consumers and audiophiles seeking \"The Magic of Innovation.\" Th...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["landing-page"],
    accentColor: "#6366F1", bgColor: "#0F0F23",
  },
  {
    id: "lp_13", slug: "lp_13",
    title: "Glassmorphic", subtitle: "Product Discovery & Visual Hero",
    category: "Landing Pages", subCategory: "SaaS / Software Product",
    style: "Dynamic Translucency & Bold Value Props",
    description: "This is a premium digital hub for a next-generation browser and digital-life organizer. The audience consists of tech-savvy power users, designers, and seekers of \"A More Calm Internet.\" The goal is t...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["landing-page"],
    accentColor: "#6366F1", bgColor: "#0F0F23",
  },
  {
    id: "lp_14", slug: "lp_14",
    title: "IndustrialPrecision", subtitle: "Engineering-First Showcase & Technical Deep Dive",
    category: "Landing Pages", subCategory: "SaaS / Software Product",
    style: "Deconstructed Storytelling & Performance Proof",
    description: "This is a premium digital flagship for a world-class high-performance hardware product (e.g., Vacuum, Purifier, or Hair Care). The audience consists of health-conscious homeowners and tech enthusiasts...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["landing-page"],
    accentColor: "#6366F1", bgColor: "#0F0F23",
  },
  {
    id: "lp_15", slug: "lp_15",
    title: "ElectricYouth", subtitle: "High-Energy Lifestyle Launch & FOMO Ecommerce",
    category: "Landing Pages", subCategory: "Course or Info Product",
    style: "High-Velocity Launches & Celebrity Discovery",
    description: "This is a premium digital hub for an aggressive, youth-focused consumer electronics brand. The audience consists of trend-seeking \"Gen Z\" and Millennial consumers. The goal is to provide a \"Launch Pla...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["landing-page"],
    accentColor: "#F59E0B", bgColor: "#0F0F0F",
  },
  {
    id: "lp_saas_01", slug: "lp_saas_01",
    title: "Precision Dark", subtitle: "SaaS landing page",
    category: "Landing Pages", subCategory: "SaaS / Software Product",
    style: "Engineering-First SaaS",
    description: "This is a project management and issue tracking platform built for software engineering teams at high-growth startups and mid-size tech companies. The user is a software engineer, product manager, or ...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["landing-page"],
    accentColor: "#6366F1", bgColor: "#0F0F23",
  },
  {
    id: "mulecom_01", slug: "mulecom_01",
    title: "Crafted Discovery", subtitle: "Handmade & Vintage Two-Sided Marketplace",
    category: "E-Commerce", subCategory: "Multi-Product Handmade / Artisan Store",
    style: "Trust-First Multi-Seller Marketplace",
    description: "This is a multi-vendor marketplace for handmade, vintage, and custom goods. Buyers discover products through search and category browsing, evaluate listings from independent shops, place orders, and r...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["marketplace", "handmade"],
    accentColor: "#92400E", bgColor: "#FFFDF6",
  },
  {
    id: "mulecom_02", slug: "mulecom_02",
    title: "Heritage Commerce", subtitle: "Curated Artisan Commerce Marketplace",
    category: "E-Commerce", subCategory: "Multi-Product Handmade / Artisan Store",
    style: "Craft-Led Curated Marketplace",
    description: "This is a curated artisan marketplace focused on apparel, jewelry, home décor, and handcrafted accessories. The platform combines craft storytelling with modern e-commerce execution.",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["marketplace", "handmade"],
    accentColor: "#92400E", bgColor: "#FFFDF6",
  },
  {
    id: "mulecom_03", slug: "mulecom_03",
    title: "Artisan Depth", subtitle: "Indian Craft & Fabric Marketplace",
    category: "E-Commerce", subCategory: "Multi-Product Handmade / Artisan Store",
    style: "Fabric-First Craft Commerce Marketplace",
    description: "This is a curated Indian craft marketplace spanning fabrics, sarees, apparel, handcrafted home products, and accessories. Buyers discover by category and craft, evaluate dispatch and policy details, t...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["marketplace", "handmade"],
    accentColor: "#92400E", bgColor: "#FFFDF6",
  },
  {
    id: "mulecom_04", slug: "mulecom_04",
    title: "Handmade Confidence", subtitle: "Artisan Empowerment Fashion Marketplace",
    category: "E-Commerce", subCategory: "Multi-Product Handmade / Artisan Store",
    style: "Policy-Clear Craft Marketplace",
    description: "This is an artisan-led marketplace for handcrafted clothing, accessories, and lifestyle products. The platform combines mission-driven storytelling with practical e-commerce execution.",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["marketplace", "handmade"],
    accentColor: "#92400E", bgColor: "#FFFDF6",
  },
  {
    id: "pcpp01", slug: "pcpp01",
    title: "MuseumDark", subtitle: "Cinematic Editorial Photographer",
    category: "Portfolio / Creator Site", subCategory: "Photographer",
    style: "High-Impact Visual Storytelling",
    description: "This is a premium cinematic portfolio for a world-renowned photographer and director. The audience consists of high-end commercial clients, gallery curators, and photography enthusiasts. The goal is t...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#1A1A1A", bgColor: "#FAFAFA",
  },
  {
    id: "pcpp02", slug: "pcpp02",
    title: "CreatorGrid", subtitle: "Creator-Photographer with Sidebar Navigation",
    category: "Portfolio / Creator Site", subCategory: "Photographer",
    style: "Functional Utility & Experimental Art",
    description: "This is a comprehensive creator platform for an experimental photographer and educator. The audience consists of fellow creatives looking for inspiration, students buying educational assets, and brand...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#1A1A1A", bgColor: "#FAFAFA",
  },
  {
    id: "pcpp04", slug: "pcpp04",
    title: "UniverseStory", subtitle: "Indian Editorial Photographer with Project-Led Structure",
    category: "Portfolio / Creator Site", subCategory: "Photographer",
    style: "Decentralized Narrative Photo-Essays",
    description: "This is a multi-project digital ecosystem for an acclaimed Indian editorial photographer. The audience consists of journalists, sociologists, international editors, and academics. The goal is to provi...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#1A1A1A", bgColor: "#FAFAFA",
  },
  {
    id: "pcpp05", slug: "pcpp05",
    title: "StoryBookOpulence", subtitle: "Indian Wedding Photography & Films",
    category: "Portfolio / Creator Site", subCategory: "Photographer",
    style: "Luxury Cinematic Wedding Portfolios",
    description: "This is a premium digital portfolio for a leading Indian wedding photography and film production firm. The audience consists of high-net-worth couples, wedding planners, and celebrity managers. The go...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#1A1A1A", bgColor: "#FAFAFA",
  },
  {
    id: "pcpp06", slug: "pcpp06",
    title: "IconicElegance", subtitle: "Global Luxury Wedding Photographer",
    category: "Portfolio / Creator Site", subCategory: "Photographer",
    style: "Sophisticated Cinematic Portfolios",
    description: "This is a premium digital portfolio for an internationally acclaimed wedding photographer and industry educator. The audience consists of celebrity clients, high-end fashion brands, and aspiring photo...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#1A1A1A", bgColor: "#FAFAFA",
  },
  {
    id: "pcpp07", slug: "pcpp07",
    title: "AeroPerspective", subtitle: "International Destination Wedding Photographer",
    category: "Portfolio / Creator Site", subCategory: "Photographer",
    style: "Grand Cinematic Landscapes & Portraits",
    description: "This is a premium digital portfolio for an internationally recognized destination wedding photographer and Fujifilm Ambassador. The audience consists of high-end couples planning weddings in remote lo...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#1A1A1A", bgColor: "#FAFAFA",
  },
  {
    id: "pcpp08", slug: "pcpp08",
    title: "CrewCinema", subtitle: "Indian Wedding Films & Photography Production House",
    category: "Portfolio / Creator Site", subCategory: "Photographer",
    style: "High-Energy Production & Vibrant Storytelling",
    description: "This is a premium digital hub for a major Indian wedding photography and cinematography production house. The audience consists of high-profile families, luxury wedding planners, and corporate brand m...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#1A1A1A", bgColor: "#FAFAFA",
  },
  {
    id: "pcpp09", slug: "pcpp09",
    title: "MarginaliaTimeless", subtitle: "Writer Portfolio & Literary Publication",
    category: "Portfolio / Creator Site", subCategory: "Photographer",
    style: "Long-Form Synthesis & Digital Book Aesthetic",
    description: "This is a premium digital publication and portfolio for a prolific writer of intellectual synthesis. The audience consists of lifelong learners, academics, poets, and curious minds. The goal is to pro...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#1A1A1A", bgColor: "#FAFAFA",
  },
  {
    id: "pcpp10", slug: "pcpp10",
    title: "InsiderEdge", subtitle: "Journalist Portfolio & Paid Newsletter",
    category: "Portfolio / Creator Site", subCategory: "Writer / Journalist",
    style: "High-Contrast Tech Editorial & Subscriptions",
    description: "This is a premium digital publication and portfolio for a leading technology journalist. The audience consists of tech executives, policy makers, and silicon-valley professionals. The goal is to provi...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#1A1A1A", bgColor: "#FFFEF0",
  },
  {
    id: "pcpp11", slug: "pcpp11",
    title: "AuthorialInsight", subtitle: "Journalist & Author Portfolio",
    category: "Portfolio / Creator Site", subCategory: "Writer / Journalist",
    style: "Literary Reportage & Investigative Authority",
    description: "This is a premium digital portfolio for a world-renowned investigative journalist and award-winning author. The audience consists of commissioning editors, literary agents, conference organizers, and ...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#1A1A1A", bgColor: "#FFFEF0",
  },
  {
    id: "pcpp12", slug: "pcpp12",
    title: "CanvasCV", subtitle: "Structured Writer/Creator Profile",
    category: "Portfolio / Creator Site", subCategory: "Writer / Journalist",
    style: "Editorial Professional Profiles & Visual Timelines",
    description: "This is a professional profile platform designed as a \"Living Resume\" for creators, developers, and writers. The audience consists of hiring managers, potential collaborators, and peer networks. The g...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#1A1A1A", bgColor: "#FFFEF0",
  },
  {
    id: "pcpp13", slug: "pcpp13",
    title: "AnalystAusterity", subtitle: "Premium Newsletter & Business Analysis",
    category: "Portfolio / Creator Site", subCategory: "Writer / Journalist",
    style: "High-Value Synthesis & Subscription Engines",
    description: "This is a premium digital publication and portfolio for a leading business analyst. The audience consists of tech executives, investors, and product managers. The goal is to provide a \"Knowledge Base\"...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#1A1A1A", bgColor: "#FFFEF0",
  },
  {
    id: "pcpp14", slug: "pcpp14",
    title: "AnalyticalKen", subtitle: "Premium Business Journalism & Newsletter",
    category: "Portfolio / Creator Site", subCategory: "Writer / Journalist",
    style: "High-Trust Business Reporting & Visual Stories",
    description: "This is a premium digital publication and portfolio for a leading business journalism firm. The audience consists of startup founders, corporate executives, and venture capitalists in India and Southe...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#1A1A1A", bgColor: "#FFFEF0",
  },
  {
    id: "pcpp15", slug: "pcpp15",
    title: "SubStackHub", subtitle: "Modern Newsletter Landing Page & Creator Hub",
    category: "Portfolio / Creator Site", subCategory: "Writer / Journalist",
    style: "Content-First Indie Publishing & Subscriptions",
    description: "This is a premium digital publication and creator hub for an independent writer or small editorial team. The audience consists of dedicated readers, industry peers, and paid subscribers. The goal is t...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#1A1A1A", bgColor: "#FFFEF0",
  },
  {
    id: "pcpp16", slug: "pcpp16",
    title: "BuilderGarden", subtitle: "Personal Site + Newsletter + Courses",
    category: "Portfolio / Creator Site", subCategory: "Personal Blog / Newsletter",
    style: "Digital Library & Educational Product Hub",
    description: "This is a premium digital hub for a modern creator-entrepreneur. The audience consists of developers, startup founders, and lifelong learners interested in AI, philosophy, and productivity. The goal i...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#0F172A", bgColor: "#F8FAFC",
  },
  {
    id: "pcpp17", slug: "pcpp17",
    title: "ReforgeElite", subtitle: "Premium Course Landing Page & Professional Network",
    category: "Portfolio / Creator Site", subCategory: "Personal Blog / Newsletter",
    style: "Peer-Driven Growth & Artifact-Led Learning",
    description: "This is a premium career-growth platform and membership hub for high-performing tech professionals. The audience consists of \"Operators\"-individuals currently in the trenches at top-tier startups and ...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#0F172A", bgColor: "#F8FAFC",
  },
  {
    id: "pcpp18", slug: "pcpp18",
    title: "CohortHub", subtitle: "Course Marketplace & Cohort Landing Pages",
    category: "Portfolio / Creator Site", subCategory: "Personal Blog / Newsletter",
    style: "Instructor-Led Learning & Transformative Sprints",
    description: "This is a premium course marketplace and landing page system for world-class, cohort-based education. The audience consists of mid-to-senior professionals (PMs, Engineers, Designers) looking for \"Care...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#0F172A", bgColor: "#F8FAFC",
  },
  {
    id: "pcpp19", slug: "pcpp19",
    title: "ExamMaster", subtitle: "Exam-Prep Edtech Discovery & Detail Pages",
    category: "Portfolio / Creator Site", subCategory: "Personal Blog / Newsletter",
    style: "High-Trust Goal-Based Learning & Subscriptions",
    description: "This is a premium digital hub for a leading competitive exam preparation platform. The audience consists of millions of Indian students (Aspirants) targeting exams like UPSC, IIT-JEE, and NEET. The go...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#0F172A", bgColor: "#F8FAFC",
  },
  {
    id: "pcpp20", slug: "pcpp20",
    title: "ROIMaster", subtitle: "Career-Focused Edtech & ROI-Led Landing Pages",
    category: "Portfolio / Creator Site", subCategory: "Personal Blog / Newsletter",
    style: "Career Transformations & University-Certified Growth",
    description: "This is a premium digital hub for a leading higher-education and upskilling platform. The audience consists of mid-career professionals, tech founders, and aspiring managers looking for \"Double Creden...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#0F172A", bgColor: "#F8FAFC",
  },
  {
    id: "pcpp21", slug: "pcpp21",
    title: "ConfigStyle", subtitle: "Premium Event Landing Page & Schedule Hub",
    category: "Portfolio / Creator Site", subCategory: "Personal Blog / Newsletter",
    style: "High-Impact Design Events & Community Hubs",
    description: "This is a premium digital hub for a global design and technology conference. The audience consists of product designers, developers, creative leads, and startup founders. The goal is to provide a \"Hyp...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["website"],
    accentColor: "#0F172A", bgColor: "#F8FAFC",
  },
  {
    id: "pfecomm_01", slug: "pfecomm_01",
    title: "Editorial Luxury", subtitle: "Premium Fashion Retail Storefront",
    category: "E-Commerce", subCategory: "Multi-Product Fashion / Apparel Store",
    style: "Premium Multi-Brand Fashion Storefront",
    description: "This is a premium fashion e-commerce storefront for a multi-brand women's fashion retailer. The brand operates five house labels under a parent brand identity: a main line and four sub-brands with dis...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["fashion", "ecommerce"],
    accentColor: "#1A1A1A", bgColor: "#FAFAFA",
  },
  {
    id: "pfecomm_02", slug: "pfecomm_02",
    title: "Warm Craft", subtitle: "Indian Heritage Fashion Storefront",
    category: "E-Commerce", subCategory: "Multi-Product Fashion / Apparel Store",
    style: "Indian Heritage Fashion E-Commerce",
    description: "This is an Indian heritage fashion e-commerce storefront for a craft-first multi-category retailer. Products are handcrafted by artisan communities across India: hand-block printed, handloom woven, na...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["fashion", "ecommerce"],
    accentColor: "#1A1A1A", bgColor: "#FAFAFA",
  },
  {
    id: "pfecomm_03", slug: "pfecomm_03",
    title: "Bold Discount", subtitle: "Indian Mass-Market Fashion Marketplace",
    category: "E-Commerce", subCategory: "Multi-Product Fashion / Apparel Store",
    style: "Indian Multi-Brand Fashion Marketplace",
    description: "This is a multi-brand Indian fashion marketplace with thousands of products across hundreds of brands. Primary categories: Women's (ethnic, western, sportswear), Men's (casual, formal, sportswear), Ki...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["fashion", "ecommerce"],
    accentColor: "#1A1A1A", bgColor: "#FAFAFA",
  },
  {
    id: "pfecomm_04", slug: "pfecomm_04",
    title: "Bold Yellow", subtitle: "Indian D2C Youth Fashion Brand",
    category: "E-Commerce", subCategory: "Multi-Product Fashion / Apparel Store",
    style: "Indian D2C Graphic Fashion Storefront",
    description: "This is a D2C graphic fashion brand targeting Indian Gen-Z and millennials. Single brand, own-label products: graphic T-shirts, hoodies, sweatshirts, joggers, shorts, and casual dresses. Products are ...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["fashion", "ecommerce"],
    accentColor: "#1A1A1A", bgColor: "#FAFAFA",
  },
  {
    id: "portfolio_01", slug: "portfolio_01",
    title: "Interactive 3D World Portfolio", subtitle: "Bruno Simon",
    category: "Portfolio / Creator Site", subCategory: "Designer / Illustrator",
    style: "Interactive 3D World Portfolio",
    description: "A single-page interactive portfolio built as a navigable 3D world. No pages, no scrolling - the visitor drives a physics-enabled car using WASD/arrow keys (or on-screen joystick on mobile) through a m...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["portfolio", "creative"],
    accentColor: "#7C3AED", bgColor: "#0D0D0D",
  },
  {
    id: "portfolio_02", slug: "portfolio_02",
    title: "Editorial Grid Portfolio", subtitle: "Jen Simmons",
    category: "Portfolio / Creator Site", subCategory: "Designer / Illustrator",
    style: "Editorial Grid Portfolio",
    description: "A personal portfolio for a designer who also writes and speaks about web technologies. The site is itself a demonstration of advanced CSS - intrinsic grid layouts, fluid typography with clamp() and ca...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["portfolio", "creative"],
    accentColor: "#7C3AED", bgColor: "#0D0D0D",
  },
  {
    id: "portfolio_03", slug: "portfolio_03",
    title: "Studio Portfolio with Case Studies", subtitle: "Locomotive",
    category: "Portfolio / Creator Site", subCategory: "Designer / Illustrator",
    style: "Studio Portfolio with Case Studies",
    description: "A multi-page studio portfolio with: (1) homepage with video hero and featured work, (2) work index with filterable case studies, (3) individual case study pages with project narrative, (4) about/agenc...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["portfolio", "creative"],
    accentColor: "#7C3AED", bgColor: "#0D0D0D",
  },
  {
    id: "portfolio_04", slug: "portfolio_04",
    title: "Studio Lotus (Indian Architecture + Interiors)", subtitle: "Category A: 8 Platform Versions",
    category: "Portfolio / Creator Site", subCategory: "Designer / Illustrator",
    style: "Studio Lotus (Indian Architecture + Interiors)",
    description: "Source: https://www.studiolotus.in Type: Interdisciplinary architecture and interior design practice portfolio Distinguishing traits: Dual-discipline taxonomy (Architecture / Interiors / Adaptive Reus...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["portfolio", "creative"],
    accentColor: "#7C3AED", bgColor: "#0D0D0D",
  },
  {
    id: "portfolio_05", slug: "portfolio_05",
    title: "Lee Robinson (Developer Personal Site + Blog)", subtitle: "Category A: 8 Platform Versions",
    category: "Portfolio / Creator Site", subCategory: "Designer / Illustrator",
    style: "Lee Robinson (Developer Personal Site + Blog)",
    description: "Source: https://leerob.com Type: Developer personal site - writing-first, content-driven, minimal Distinguishing traits: Extreme minimalism (pure typography, no graphics), blog/writing IS the portfoli...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["portfolio", "creative"],
    accentColor: "#7C3AED", bgColor: "#0D0D0D",
  },
  {
    id: "portfolio_06", slug: "portfolio_06",
    title: "Brittany Chiang (Iconic Developer Portfolio)", subtitle: "Category A: 8 Platform Versions",
    category: "Portfolio / Creator Site", subCategory: "Designer / Illustrator",
    style: "Brittany Chiang (Iconic Developer Portfolio)",
    description: "Source: https://brittanychiang.com Type: Single-page developer portfolio with sticky two-column layout and scroll-spy navigation Distinguishing traits: Dark navy + teal palette, sticky left panel with...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["portfolio", "creative"],
    accentColor: "#7C3AED", bgColor: "#0D0D0D",
  },
  {
    id: "portfolio_07", slug: "portfolio_07",
    title: "Josh W. Comeau (Design-Forward Developer Blog)", subtitle: "Category A: 8 Platform Versions",
    category: "Portfolio / Creator Site", subCategory: "Designer / Illustrator",
    style: "Josh W. Comeau (Design-Forward Developer Blog)",
    description: "Source: https://www.joshwcomeau.com Type: Design-forward developer blog with interactive tutorials and courses Distinguishing traits: HSL-based CSS custom property color system, dark/light mode via in...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["portfolio", "creative"],
    accentColor: "#7C3AED", bgColor: "#0D0D0D",
  },
  {
    id: "portfolio_08", slug: "portfolio_08",
    title: "Tania Rascia", subtitle: "Self-Taught Developer: Content + Portfolio Mix",
    category: "Portfolio / Creator Site", subCategory: "Designer / Illustrator",
    style: "Tania Rascia",
    description: "Build a developer blog and portfolio site for a prolific self-taught developer and technical writer. The site is a content-first digital garden - the value is in the accumulated writing, not in visual...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["portfolio", "creative"],
    accentColor: "#7C3AED", bgColor: "#0D0D0D",
  },
  {
    id: "saas_platform_01", slug: "saas_platform_01",
    title: "Engineering-First", subtitle: "Project Management and Issue Tracking SaaS",
    category: "Apps & SaaS Interface", subCategory: "Dashboard Layout",
    style: "Project Management and Issue Tracking Platform",
    description: "This is a project management and issue tracking SaaS platform for software engineering teams. Teams create, assign, prioritize, and track issues. Work is organized into cycles (time-boxed sprints) and...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["saas", "app"],
    accentColor: "#6366F1", bgColor: "#0F0F23",
  },
  {
    id: "sbecom_01", slug: "sbecom_01",
    title: "FreshZest", subtitle: "Subscription Meal-Kit Storefront",
    category: "E-Commerce", subCategory: "Subscription Box Site",
    style: "Vibrant Subscription & Meal Onboarding",
    description: "This is a meal-kit subscription platform where users sign up for weekly boxes of fresh ingredients and recipes. The customer is a busy professional or a family looking to eat healthy, home-cooked meal...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["subscription", "ecommerce"],
    accentColor: "#DC2626", bgColor: "#FFF8F0",
  },
  {
    id: "sbecom_02", slug: "sbecom_02",
    title: "ChaiRitual", subtitle: "High-Frequency FMCG Subscription",
    category: "E-Commerce", subCategory: "Subscription Box Site",
    style: "Modern Indian Tea & Pantry Subscription",
    description: "This is an omnichannel \"Home Cafe\" subscription storefront for a premium Indian tea brand. The customer is a daily tea drinker-ranging from the WFH professional to the large Indian family-who values c...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["subscription", "ecommerce"],
    accentColor: "#DC2626", bgColor: "#FFF8F0",
  },
  {
    id: "sbecom_03", slug: "sbecom_03",
    title: "GlowProfile", subtitle: "Personalized Beauty Subscription",
    category: "E-Commerce", subCategory: "Subscription Box Site",
    style: "Data-Driven Beauty Discovery",
    description: "This is a personalized beauty subscription storefront that uses a \"Beauty Profile\" to deliver tailored samples. The customer is a \"Beauty Explorer\"-someone who loves trying new products but feels over...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["subscription", "ecommerce"],
    accentColor: "#DC2626", bgColor: "#FFF8F0",
  },
  {
    id: "sbecom_04", slug: "sbecom_04",
    title: "BlueChef", subtitle: "Premium Culinary Subscription",
    category: "E-Commerce", subCategory: "Subscription Box Site",
    style: "Professional Meal Kits & Wine Pairings",
    description: "This is a high-end meal kit platform that delivers chef-designed recipes and sustainably sourced ingredients. A key differentiator is the integrated \"Wine Cellar\" subscription, where wines are curated...",
    stack: ["Next.js 14", "Tailwind", "TypeScript"],
    screenshot: "", rating: 4.8, tested: true,
    tags: ["subscription", "ecommerce"],
    accentColor: "#DC2626", bgColor: "#FFF8F0",
  },
];
