import type { LockTemplate } from "../types.js";
import { productNegativeLocks } from "../negatives/product.js";

export const productLockTemplate: LockTemplate = {
  categoryId: "product-ecommerce",
  categoryLabel: "Product & Ecommerce",
  purpose:
    "Protect the product form, orientation, scale, visibility, material, and brand feel across model variants.",
  mandatoryLocks: [
    {
      key: "product",
      label: "Product",
      required: true,
      description: "The hero product the shot is fundamentally about.",
      extractionHints: ["bottle", "jar", "sneaker", "watch", "packaging", "device", "tote"],
    },
    {
      key: "productOrientation",
      label: "Orientation",
      required: true,
      description: "How the product faces the camera so its identity stays recognizable.",
      extractionHints: ["front-facing", "three-quarter", "label to camera", "upright", "top-down", "flat lay"],
    },
    {
      key: "scale",
      label: "Scale",
      required: true,
      description: "How large the product reads in frame.",
      extractionHints: ["macro", "fills the frame", "hero scale", "life-size", "miniature"],
    },
    {
      key: "productPosition",
      label: "Position",
      required: true,
      description: "Where the product sits within the frame.",
      extractionHints: ["centered", "off-center", "lower third", "rule of thirds", "left third"],
    },
    {
      key: "composition",
      label: "Composition",
      required: true,
      description: "The framing logic of the shot.",
      extractionHints: ["packshot", "hero shot", "flat lay", "close-up", "knolling"],
    },
    {
      key: "background",
      label: "Background",
      required: true,
      description: "The surface or backdrop the product sits against.",
      extractionHints: ["seamless studio", "marble", "stone surface", "gradient", "concrete", "wood"],
    },
    {
      key: "lighting",
      label: "Lighting",
      required: true,
      description: "The lighting setup that defines the product's material read.",
      extractionHints: ["softbox", "studio strobe", "rim light", "high-key", "low-key", "soft window"],
    },
    {
      key: "material",
      label: "Material",
      required: true,
      description: "How the product surface and physical realism should behave.",
      extractionHints: ["matte", "glossy", "glass", "ceramic", "brushed metal", "frosted", "leather"],
    },
    {
      key: "brandStyle",
      label: "Brand Style",
      required: true,
      description: "The commercial or editorial brand language the image must preserve.",
      extractionHints: ["minimal", "luxury", "premium", "playful", "Apple-style", "editorial commercial"],
    },
  ],
  optionalLocks: [
    {
      key: "productVisibility",
      label: "Visibility",
      required: false,
      description: "What of the product stays unobstructed — only when the prompt states it.",
      extractionHints: ["full product visible", "label visible", "cap visible", "unobstructed", "logo readable"],
    },
    {
      key: "surface",
      label: "Surface",
      required: false,
      description: "Useful when reflections, gloss, or texture under the product matter.",
    },
    {
      key: "palette",
      label: "Palette",
      required: false,
      description: "Useful when brand color identity is central to the shot.",
    },
    {
      key: "props",
      label: "Props",
      required: false,
      description: "Useful when supporting props are part of the staged scene.",
    },
    {
      key: "cameraAngle",
      label: "Camera Angle",
      required: false,
      description: "Useful when eye-level, top-down, or low-angle hero is central.",
    },
    {
      key: "crop",
      label: "Crop",
      required: false,
      description: "Useful when a specific aspect ratio or banner crop matters.",
    },
  ],
  locksToAvoid: [
    "Exact specular highlight percentages",
    "Drape-angle or seam-spacing micrometrics",
    "Coordinate systems as a default product lock",
    "Lens-height micrometrics unless absolutely necessary",
  ],
  extractionRules: [
    "Prefer explicit description-layer facts over inferred product traits.",
    "Treat the named object (bottle, jar, sneaker, packaging) as the product.",
    "Separate orientation (how it faces) from position (where it sits in frame).",
    "Map surface words like marble, stone, seamless, gradient, or wood into background.",
    "Treat matte, glossy, glass, ceramic, or metal as material, not style.",
    "Treat minimal, luxury, premium, or commercial cues as brand style.",
  ],
  defaultNegativeLocks: productNegativeLocks,
  examples: [
    {
      promptTitle: "Matte Ceramic Mug Hero Shot",
      extracted: {
        product: "Matte ceramic mug",
        productOrientation: "Three-quarter, handle to camera-right",
        scale: "Hero scale, fills most of the frame",
        productPosition: "Centered",
        productVisibility: "Full mug and handle visible",
        composition: "Studio packshot",
        background: "Seamless stone surface",
        lighting: "Soft studio softbox with gentle rim light",
        material: "Matte ceramic",
        brandStyle: "Minimal premium commercial",
      },
      notes: "Anchor example for the product parser.",
    },
    {
      promptTitle: "Glass Perfume Bottle Editorial",
      extracted: {
        product: "Glass perfume bottle",
        productOrientation: "Front-facing, label to camera",
        scale: "Macro hero scale",
        productPosition: "Lower third",
        productVisibility: "Label and cap unobstructed",
        composition: "Close-up hero shot",
        background: "Gradient studio backdrop",
        lighting: "Low-key studio strobe with rim light",
        material: "Frosted glass",
        brandStyle: "Luxury editorial",
      },
    },
  ],
};
