export type Family = "image" | "video" | "text" | "content" | "website";

export interface PromptItem {
  id: string;
  slug?: string;
  title: string;
  description: string;
  image: string;
  category: string;
  subCategory: string;
  family?: Family;
  tested: boolean;
  rating: number;
  reviews: number;
  platforms: Record<string, string>;
  variables: { name: string; placeholder: string }[];
  tags: string[];
  author: string;
}

export const categories = {
  video: [
    { name: "Cinematic & Film",            subs: ["Short Films", "Movie Trailers", "Cinematic Scenes", "Documentary Style Videos", "Music Videos"] },
    { name: "Advertising & Commercial",    subs: ["Brand Advertisements", "TV Commercials", "Promotional Videos", "Corporate Commercials", "Event Promotion Videos"] },
    { name: "Social Media Videos",         subs: ["Instagram Reels", "TikTok Videos", "YouTube Shorts", "Influencer Content", "Lifestyle & Vlog Videos"] },
    { name: "Product & E-Commerce Videos", subs: ["Product Demonstrations", "Product Showcases", "Unboxing Videos", "Product Launch Videos", "Customer Testimonial Videos"] },
    { name: "Education & Explainers",      subs: ["Explainer Videos", "Tutorial Videos", "Educational Animations", "Whiteboard Explainers", "Training Videos"] },
    { name: "Creative & Entertainment",    subs: ["Animated Stories", "Comedy Skits", "Gaming Videos", "Character Animations", "Music Visualizers"] },
  ],
  image: [
    { name: "Design Outputs", subs: ["Poster", "Banner", "Social Media"] },
    { name: "Photography", subs: ["Portrait", "Landscape", "Product"] },
    { name: "Illustration", subs: ["Character", "Scene", "Abstract"] },
    { name: "Video Storyboards", subs: ["Ad", "Trailer", "Short Film"] },
  ],
  website: [
    { name: "Landing Pages",          subs: ["SaaS / Software Product", "Physical Product Launch Page", "Personal Brand / Creator", "Course or Info Product", "Event / Conference"] },
    { name: "Business Website",        subs: ["Restaurant / Cafe", "Doctor / Clinic / Hospital", "Lawyer / CA / Consulting", "Boutique / Retail Store", "Real Estate / Property Listing", "Educational Institute / Coaching Centre"] },
    { name: "Portfolio / Creator Site", subs: ["Photographer", "Designer / Illustrator", "Writer / Journalist", "Developer / Engineer", "Personal Blog / Newsletter"] },
    { name: "E-Commerce",             subs: ["Single Product (Shopify-style)", "Multi-Product Fashion / Apparel Store", "Multi-Product Handmade / Artisan Store", "Subscription Box Site", "Digital Product Store"] },
    { name: "Apps & SaaS Interface",  subs: ["Dashboard Layout", "Onboarding Flow Screens", "Settings / Account Page", "Pricing Page", "Blog / Content Layout"] },
    { name: "Reusable Sections",      subs: ["Hero Section", "Features / Benefits Section", "Pricing Table", "Testimonial Section", "FAQ Section", "Footer Design", "Navigation / Header Pattern"] },
  ],
  text: [
    { name: "Developers", subs: ["Debug", "Refactor", "Document", "Test"] },
    { name: "Marketing", subs: ["Copy", "Email", "Social", "Ad"] },
    { name: "HR & Recruiting", subs: ["Job Description", "Interview", "Onboarding"] },
    { name: "Data & Analytics", subs: ["SQL", "Report", "Summary", "Insight"] },
    { name: "Education", subs: ["Lesson Plan", "Quiz", "Feedback", "Rubric"] },
    { name: "Product", subs: ["PRD", "User Story", "Roadmap", "Spec"] },
    { name: "Legal", subs: ["Contract", "Policy", "Review", "Compliance"] },
    { name: "Finance", subs: ["Report", "Forecast", "Analysis", "Model"] },
  ],
};

export const platforms = [
  { key: "chatgpt",     name: "ChatGPT",    color: "#10a37f" },
  { key: "gemini",      name: "Gemini",     color: "#4285f4" },
  { key: "grok",        name: "Grok",       color: "#094067" },
  { key: "midjourney",  name: "Midjourney", color: "#ef4565" },
  { key: "firefly",     name: "Firefly",    color: "#ffd803" },
  { key: "flux",        name: "FLUX",       color: "#90b4ce" },
];

export const videoPlatforms = [
  { key: "veo",        name: "Veo",        color: "#4285f4" },
  { key: "kling",      name: "Kling",      color: "#1a1a2e" },
  { key: "seedance",   name: "Seedance",   color: "#e94560" },
  { key: "higgsfield", name: "Higgsfield", color: "#7c3aed" },
  { key: "pika",       name: "Pika Labs",  color: "#f59e0b" },
];

export const websitePlatforms = [
  { key: "lovable",  name: "Lovable",         color: "#ff4d8f" },
  { key: "bolt",     name: "Bolt.new",        color: "#7c3aed" },
  { key: "v0",       name: "v0",              color: "#000000" },
  { key: "cursor",   name: "Cursor",          color: "#1a1a2e" },
  { key: "chatgpt",  name: "ChatGPT Canvas",  color: "#10a37f" },
  { key: "claude",   name: "Claude Artifacts",color: "#cc785c" },
  { key: "gemini",   name: "Gemini",          color: "#4285f4" },
  { key: "grok",     name: "Grok",            color: "#094067" },
];

export const familyCategories: Record<Family, string[]> = {
  image:   ["Design Outputs", "Photography", "Illustration", "Video Storyboards"],
  video:   ["Cinematic & Film", "Advertising & Commercial", "Social Media Videos", "Product & E-Commerce Videos", "Education & Explainers", "Creative & Entertainment"],
  text:    ["Developers", "Data & Analytics", "Education", "Product", "Legal", "Finance"],
  content: ["Marketing", "HR & Recruiting"],
  website: ["Landing Pages", "Business Website", "Portfolio / Creator Site", "E-Commerce", "Apps & SaaS Interface", "Reusable Sections"],
};

export const familyMeta: Record<Family, { title: string }> = {
  image:   { title: "Image Generation Prompts" },
  video:   { title: "Video Generation Prompts" },
  text:    { title: "Text Generation Prompts" },
  content: { title: "Content Generation Prompts" },
  website: { title: "Website Generation Prompts" },
};

export const samplePrompts: PromptItem[] = [
  {
    id: "p-001",
    title: "Cinematic Event Poster",
    description: "Creates a dramatic, high-impact event poster with editorial lighting and bold type hierarchy.",
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=75",
    category: "Design Outputs",
    subCategory: "Poster",
    tested: true,
    rating: 4.9,
    reviews: 312,
    platforms: {
      chatgpt:    "Create a cinematic event poster for [subject] with [mood] lighting and [style] aesthetic. Include bold typography. Format: 2:3.",
      midjourney: "[subject] event poster, [mood] rim lighting, bold editorial typography, [style] --ar 2:3 --v6 --style raw --q 2",
      flux:       "Ultra-detailed [subject] event poster, [mood] dramatic lighting, [style] composition, editorial typography, photorealistic 8K, aspect 2:3.",
      gemini:     "Design a [mood] event poster for [subject] in [style] visual style with strong typographic layout.",
      grok:       "[subject] poster, [mood], [style] look.",
      firefly:    "Event poster for [subject], [mood] mood, [style] style.",
    },
    variables: [
      { name: "subject",  placeholder: "e.g. tech summit 2026" },
      { name: "mood",     placeholder: "e.g. dramatic, ethereal" },
      { name: "style",    placeholder: "e.g. minimalist, bauhaus" },
    ],
    tags: ["poster", "design", "event", "cinematic", "editorial"],
    author: "Kishore",
  },
  {
    id: "p-002",
    title: "Java Debug Assistant",
    description: "Analyzes Java code, identifies root causes, explains the issue, and returns an improved version.",
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=75",
    category: "Developers",
    subCategory: "Debug",
    tested: true,
    rating: 4.8,
    reviews: 248,
    platforms: {
      chatgpt:    "Act as a senior Java developer. Analyze the following code, identify the root cause of the issue, explain it clearly, and provide an optimized corrected version.\n\n[code]",
      gemini:     "You are a Java expert. Review this code for bugs, explain each issue, and return a fixed version.\n\n[code]",
      grok:       "Debug this Java code and fix it: [code]",
      midjourney: "(not applicable)",
      firefly:    "(not applicable)",
      flux:       "(not applicable)",
    },
    variables: [
      { name: "code", placeholder: "Paste your Java code here" },
    ],
    tags: ["java", "debug", "code", "backend", "developer"],
    author: "Sarah K.",
  },
  {
    id: "p-003",
    title: "Product Launch Email",
    description: "Generates a conversion-optimized product launch email with urgency, benefits, and a clear CTA.",
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&q=75",
    category: "Marketing",
    subCategory: "Email",
    tested: true,
    rating: 4.7,
    reviews: 189,
    platforms: {
      chatgpt: "You are a direct-response copywriter. Write a product launch email for [product] targeting [audience]. Include: subject line, preview text, 3-sentence hook, benefits, social proof, CTA. Tone: [tone].",
      gemini:  "Write a launch email for [product] aimed at [audience] with [tone] tone. Include subject line, body, and a strong CTA.",
      grok:    "Launch email for [product], audience: [audience], tone: [tone].",
      midjourney: "(not applicable)",
      firefly:    "(not applicable)",
      flux:       "(not applicable)",
    },
    variables: [
      { name: "product",  placeholder: "e.g. Prompt Bot Pro" },
      { name: "audience", placeholder: "e.g. product designers" },
      { name: "tone",     placeholder: "e.g. professional, energetic" },
    ],
    tags: ["email", "marketing", "launch", "copy", "conversion"],
    author: "Priya M.",
  },
  {
    id: "p-004",
    title: "Cyberpunk Portrait",
    description: "Generates a cinematic cyberpunk character portrait with neon lighting and atmospheric depth.",
    image: "https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=800&q=75",
    category: "Photography",
    subCategory: "Portrait",
    tested: false,
    rating: 4.6,
    reviews: 134,
    platforms: {
      midjourney: "[character] cyberpunk portrait, neon-lit, [mood] atmosphere, highly detailed, cinematic, [style] --ar 3:4 --v6 --style raw",
      flux:       "Photorealistic cyberpunk portrait of [character], neon rim lighting, [mood] mood, urban night backdrop, 85mm, f/1.8, 8K.",
      firefly:    "[character] in cyberpunk setting, neon glow, [mood] mood, [style] visual style.",
      chatgpt:    "(not applicable)",
      gemini:     "(not applicable)",
      grok:       "(not applicable)",
    },
    variables: [
      { name: "character", placeholder: "e.g. a female warrior" },
      { name: "mood",      placeholder: "e.g. intense, mysterious" },
      { name: "style",     placeholder: "e.g. hyper-real, painterly" },
    ],
    tags: ["cyberpunk", "portrait", "neon", "character", "sci-fi"],
    author: "Alex R.",
  },
  {
    id: "p-005",
    title: "Python Refactoring Guide",
    description: "Refactors messy Python code into clean, testable, well-documented functions with type hints.",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=75",
    category: "Developers",
    subCategory: "Refactor",
    tested: true,
    rating: 4.8,
    reviews: 201,
    platforms: {
      chatgpt: "Act as a senior Python engineer. Refactor the following code into clean, testable units. Add type hints, docstrings, and follow PEP-8. Explain each change.\n\n[code]",
      gemini:  "Refactor this Python code for readability and testability. Add type hints. Explain changes.\n\n[code]",
      grok:    "Clean up and refactor this Python code: [code]",
      midjourney: "(not applicable)",
      firefly:    "(not applicable)",
      flux:       "(not applicable)",
    },
    variables: [
      { name: "code", placeholder: "Paste your Python code here" },
    ],
    tags: ["python", "refactor", "clean code", "developer", "backend"],
    author: "Dev T.",
  },
  {
    id: "p-006",
    title: "Job Description Writer",
    description: "Creates inclusive, role-specific job descriptions with responsibilities, requirements and perks.",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=75",
    category: "HR & Recruiting",
    subCategory: "Job Description",
    tested: true,
    rating: 4.5,
    reviews: 97,
    platforms: {
      chatgpt: "You are an experienced HR professional. Write a [tone] job description for a [role] at [company]. Include: overview, responsibilities (5), requirements (5), preferred skills (3), benefits, and a closing statement. Avoid exclusionary language.",
      gemini:  "Write an inclusive job description for a [role] at [company] in [tone] tone. Include responsibilities, requirements, and benefits.",
      grok:    "Job description for [role] at [company], [tone] tone.",
      midjourney: "(not applicable)",
      firefly:    "(not applicable)",
      flux:       "(not applicable)",
    },
    variables: [
      { name: "role",    placeholder: "e.g. Senior Product Designer" },
      { name: "company", placeholder: "e.g. Figma" },
      { name: "tone",    placeholder: "e.g. friendly, corporate" },
    ],
    tags: ["hr", "recruiting", "job description", "hiring", "inclusive"],
    author: "Lena W.",
  },
  {
    id: "p-007",
    title: "Product Roadmap Summary",
    description: "Summarizes a complex product roadmap into executive-ready bullets with timeline and impact.",
    image: "https://images.unsplash.com/photo-1542744094-3a31f272c490?w=800&q=75",
    category: "Product",
    subCategory: "Roadmap",
    tested: false,
    rating: 4.4,
    reviews: 72,
    platforms: {
      chatgpt: "Act as a senior PM. Summarize the following roadmap for a [audience] audience in [format] format. Focus on business impact, timeline, and dependencies.\n\n[roadmap]",
      gemini:  "Summarize this product roadmap for [audience] in [format]. Highlight impact and timeline.\n\n[roadmap]",
      grok:    "Summarize this roadmap for [audience]: [roadmap]",
      midjourney: "(not applicable)",
      firefly:    "(not applicable)",
      flux:       "(not applicable)",
    },
    variables: [
      { name: "audience", placeholder: "e.g. C-suite executives" },
      { name: "format",   placeholder: "e.g. 5 bullets, table" },
      { name: "roadmap",  placeholder: "Paste your roadmap text" },
    ],
    tags: ["product", "roadmap", "PM", "summary", "strategy"],
    author: "Omar A.",
  },
  {
    id: "p-008",
    title: "Watercolor Landscape",
    description: "Generates painterly watercolor landscape art with soft edges, muted palettes, and atmospheric mood.",
    image: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&q=75",
    category: "Illustration",
    subCategory: "Scene",
    tested: false,
    rating: 4.3,
    reviews: 88,
    platforms: {
      midjourney: "[landscape], watercolor painting, soft diffused light, [mood] palette, impressionist brushwork --ar 16:9 --v6 --style raw",
      flux:       "Watercolor landscape of [landscape], [mood] light, pastel tones, soft edges, artistic texture, wide aspect ratio.",
      firefly:    "[landscape] watercolor scene, [mood] mood, painterly soft tones.",
      chatgpt:    "(not applicable)",
      gemini:     "(not applicable)",
      grok:       "(not applicable)",
    },
    variables: [
      { name: "landscape", placeholder: "e.g. misty mountain valley" },
      { name: "mood",      placeholder: "e.g. serene, golden hour" },
    ],
    tags: ["watercolor", "landscape", "painting", "illustration", "art"],
    author: "Maya S.",
  },
  {
    id: "p-009",
    title: "SQL Query Optimizer",
    description: "Analyzes slow SQL queries and rewrites them with indexes, CTEs, and performance best practices.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=75",
    category: "Data & Analytics",
    subCategory: "SQL",
    tested: true,
    rating: 4.7,
    reviews: 156,
    platforms: {
      chatgpt: "Act as a database performance expert. Analyze this SQL query for performance issues. Identify bottlenecks, suggest indexes, and rewrite as an optimized version with CTEs where appropriate.\n\n[query]",
      gemini:  "Optimize this SQL query for performance. Add indexes, use CTEs, and explain each change.\n\n[query]",
      grok:    "Optimize this SQL: [query]",
      midjourney: "(not applicable)",
      firefly:    "(not applicable)",
      flux:       "(not applicable)",
    },
    variables: [
      { name: "query", placeholder: "Paste your SQL query here" },
    ],
    tags: ["sql", "database", "query", "performance", "analytics"],
    author: "Raj P.",
  },
  {
    id: "p-010",
    title: "LinkedIn Thought Leadership Post",
    description: "Writes an engaging LinkedIn post that positions the author as a thought leader in their field.",
    image: "https://images.unsplash.com/photo-1611944212129-29977ae1398c?w=800&q=75",
    category: "Marketing",
    subCategory: "Social",
    tested: true,
    rating: 4.6,
    reviews: 143,
    platforms: {
      chatgpt: "You are a top LinkedIn creator. Write a thought leadership post about [topic] for [audience]. Open with a bold hook. Include a personal insight, a key lesson, and a question to spark comments. [tone] tone. Max 180 words.",
      gemini:  "Write a LinkedIn post about [topic] for [audience]. Hook first, insight, lesson, question. [tone] tone.",
      grok:    "LinkedIn post on [topic], audience: [audience], tone: [tone].",
      midjourney: "(not applicable)",
      firefly:    "(not applicable)",
      flux:       "(not applicable)",
    },
    variables: [
      { name: "topic",    placeholder: "e.g. prompt engineering for designers" },
      { name: "audience", placeholder: "e.g. product designers, founders" },
      { name: "tone",     placeholder: "e.g. thoughtful, punchy" },
    ],
    tags: ["linkedin", "social media", "thought leadership", "content", "marketing"],
    author: "Nina L.",
  },
  {
    id: "p-011",
    title: "Brand Photography Style",
    description: "Creates consistent brand photography prompts for product and lifestyle imagery across platforms.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=75",
    category: "Photography",
    subCategory: "Product",
    tested: false,
    rating: 4.2,
    reviews: 61,
    platforms: {
      midjourney: "[product] product photography, [background] background, [lighting] lighting, brand editorial, clean composition --ar 4:3 --v6",
      flux:       "Commercial product photo of [product], [lighting] studio lighting, [background] backdrop, editorial clean composition, 8K.",
      firefly:    "[product] brand photography, [lighting] light, [background], clean modern style.",
      chatgpt:    "(not applicable)",
      gemini:     "(not applicable)",
      grok:       "(not applicable)",
    },
    variables: [
      { name: "product",    placeholder: "e.g. minimalist water bottle" },
      { name: "lighting",   placeholder: "e.g. soft diffused, rim" },
      { name: "background", placeholder: "e.g. white seamless, marble" },
    ],
    tags: ["photography", "product", "brand", "commercial", "studio"],
    author: "Emma C.",
  },
  {
    id: "p-012",
    title: "Unit Test Generator",
    description: "Generates comprehensive unit tests with edge cases, mocks, and assertions for any function.",
    image: "https://images.unsplash.com/photo-1555099962-4199c345e5dd?w=800&q=75",
    category: "Developers",
    subCategory: "Test",
    tested: true,
    rating: 4.9,
    reviews: 277,
    platforms: {
      chatgpt: "Act as a senior QA engineer. Generate comprehensive unit tests for the following [language] function. Cover: happy path, edge cases, null/empty inputs, error states. Use [framework]. Add clear test descriptions.\n\n[code]",
      gemini:  "Generate unit tests for this [language] function using [framework]. Cover edge cases and error states.\n\n[code]",
      grok:    "Write unit tests for this [language] code using [framework]: [code]",
      midjourney: "(not applicable)",
      firefly:    "(not applicable)",
      flux:       "(not applicable)",
    },
    variables: [
      { name: "language",  placeholder: "e.g. TypeScript, Python" },
      { name: "framework", placeholder: "e.g. Jest, pytest" },
      { name: "code",      placeholder: "Paste your function here" },
    ],
    tags: ["testing", "unit test", "QA", "developer", "automation"],
    author: "Chris B.",
  },
  {
    id: "p-013",
    title: "SaaS Landing Page Copy",
    description: "Generates full landing page copy — hero, features, social proof, pricing, and CTA — for any SaaS product.",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=75",
    category: "Landing Pages",
    subCategory: "SaaS",
    tested: true,
    rating: 4.8,
    reviews: 193,
    platforms: {
      chatgpt: "You are a conversion copywriter. Write full landing page copy for [product], a SaaS tool for [audience]. Include: hero headline + subheading, 3 feature blocks with benefits, social proof section, pricing section intro, and a closing CTA. Tone: [tone].",
      gemini:  "Write SaaS landing page copy for [product] targeting [audience]. Cover: hero, features (3), social proof, and CTA. Tone: [tone].",
      grok:    "Landing page copy for [product], audience: [audience], tone: [tone]. Hero, features, CTA.",
      midjourney: "(not applicable)",
      firefly:    "(not applicable)",
      flux:       "(not applicable)",
    },
    variables: [
      { name: "product",  placeholder: "e.g. Prompt Bot" },
      { name: "audience", placeholder: "e.g. designers and developers" },
      { name: "tone",     placeholder: "e.g. bold and minimal, friendly" },
    ],
    tags: ["landing page", "saas", "website", "copy", "conversion"],
    author: "The BOT Company",
  },
  {
    id: "p-014",
    title: "React Component from Description",
    description: "Generates a production-ready React component from a plain-English UI description — ready for v0, Bolt, or Lovable.",
    image: "https://images.unsplash.com/photo-1621839673705-6617adf9e890?w=800&q=75",
    category: "UI Components",
    subCategory: "Hero",
    tested: true,
    rating: 4.7,
    reviews: 164,
    platforms: {
      chatgpt: "You are a senior React developer. Build a production-ready [component] component using Tailwind CSS. Requirements: [requirements]. Use TypeScript, proper props interface, and clean semantic HTML. No external libraries beyond React and Tailwind.",
      gemini:  "Build a [component] React component with Tailwind CSS. Requirements: [requirements]. TypeScript, clean props, semantic HTML.",
      grok:    "React + Tailwind [component] component. Requirements: [requirements].",
      midjourney: "(not applicable)",
      firefly:    "(not applicable)",
      flux:       "(not applicable)",
    },
    variables: [
      { name: "component",    placeholder: "e.g. hero section, pricing table" },
      { name: "requirements", placeholder: "e.g. dark mode, animated CTA, mobile-first" },
    ],
    tags: ["react", "component", "tailwind", "ui", "website", "frontend"],
    author: "The BOT Company",
  },
];
