import type { LockTemplate } from "../types.js";
import { fashionNegativeLocks } from "../negatives/fashion.js";

export const fashionLockTemplate: LockTemplate = {
  categoryId: "fashion-apparel",
  categoryLabel: "Fashion & Apparel",
  purpose: "Protect the garment first and the model second across model variants.",
  mandatoryLocks: [
    {
      key: "subject",
      label: "Model",
      required: true,
      description: "Who wears the garment — the model carrying the look.",
      extractionHints: ["female model", "male model", "androgynous model", "street-cast model"],
    },
    {
      key: "garment",
      label: "Garment",
      required: true,
      description: "The hero garment or outfit the shot is fundamentally about.",
      extractionHints: ["trench coat", "slip dress", "tailored suit", "saree", "denim jacket"],
    },
    {
      key: "garmentColor",
      label: "Garment Color",
      required: true,
      description: "The garment color identity that must not drift.",
      extractionHints: ["emerald", "crimson", "ivory", "charcoal", "navy", "mustard"],
      warning: "Garment color was not clearly extracted; color identity may drift across platforms.",
    },
    {
      key: "garmentFit",
      label: "Garment Fit",
      required: true,
      description: "The silhouette and fit that define the look.",
      extractionHints: ["tailored", "oversized", "slim-fit", "flowing", "draped", "structured"],
    },
    {
      key: "composition",
      label: "Composition",
      required: true,
      description: "The framing logic that preserves how the look is presented.",
      extractionHints: ["full-body", "three-quarter", "waist-up", "runway", "centered"],
    },
    {
      key: "lighting",
      label: "Lighting",
      required: true,
      description: "The lighting setup that defines the editorial or commercial mood.",
      extractionHints: ["soft daylight", "studio softbox", "hard editorial", "runway light", "golden hour"],
    },
    {
      key: "material",
      label: "Fabric",
      required: true,
      description: "How the fabric and its surface should behave physically.",
      extractionHints: ["silk", "denim", "linen", "wool", "chiffon", "velvet", "leather"],
    },
    {
      key: "styleDna",
      label: "Style DNA",
      required: true,
      description: "The editorial or brand language the image must preserve.",
      extractionHints: ["Vogue editorial", "runway", "streetwear", "haute couture", "lookbook"],
      warning: "Style DNA was not clearly extracted; assembled output may drift across platforms.",
    },
  ],
  optionalLocks: [
    {
      key: "pose",
      label: "Pose",
      required: false,
      description: "Model pose — only when a model is present (absent on flat/accessory shots).",
      extractionHints: ["walking", "leaning", "hand on hip", "three-quarter turn", "standing"],
    },
    {
      key: "garmentVisibility",
      label: "Garment Visibility",
      required: false,
      description: "How much of the garment is visible — only when the framing implies it.",
      extractionHints: ["full-length visible", "head-to-toe", "cropped at waist", "full outfit visible"],
    },
    {
      key: "handPosition",
      label: "Hand Position",
      required: false,
      description: "Visible hand behavior — only relevant when hands appear in frame.",
      extractionHints: ["hand on hip", "hands in pockets", "adjusting collar", "arms crossed"],
    },
    {
      key: "background",
      label: "Background",
      required: false,
      description: "Useful when the location or backdrop frames the look.",
    },
    {
      key: "expression",
      label: "Expression",
      required: false,
      description: "Useful when the model's expression is part of the campaign tone.",
    },
    {
      key: "gaze",
      label: "Gaze",
      required: false,
      description: "Useful when eye contact or off-camera gaze is intentional.",
    },
    {
      key: "crop",
      label: "Crop",
      required: false,
      description: "Useful when a specific aspect ratio or banner crop matters.",
    },
    {
      key: "palette",
      label: "Palette",
      required: false,
      description: "Useful when a broader color story beyond the garment matters.",
    },
  ],
  locksToAvoid: [
    "Exact seam-spacing or stitch-count metrics",
    "Drape-angle degrees as a default lock",
    "Coordinate systems as a default fashion lock",
    "Micro facial percentages on the model",
  ],
  extractionRules: [
    "Protect the garment before the model — garment fields are mandatory.",
    "Separate garment color (identity) from palette (broader color story).",
    "Separate fit (silhouette) from fabric (material behavior).",
    "Map location phrases like studio, street, runway, or rooftop into background.",
    "Treat Vogue, runway, streetwear, lookbook, or campaign cues as style DNA.",
  ],
  defaultNegativeLocks: fashionNegativeLocks,
  examples: [
    {
      promptTitle: "Emerald Slip Dress Editorial",
      extracted: {
        subject: "Female model",
        garment: "Silk slip dress",
        garmentVisibility: "Full-length garment visible",
        garmentColor: "Emerald",
        garmentFit: "Flowing bias-cut fit",
        pose: "Three-quarter turn, hand on hip",
        handPosition: "Hand on hip",
        composition: "Full-body editorial",
        lighting: "Soft daylight",
        material: "Silk",
        styleDna: "Vogue editorial",
      },
      notes: "Anchor example for the fashion parser.",
    },
    {
      promptTitle: "Oversized Denim Streetwear Look",
      extracted: {
        subject: "Street-cast model",
        garment: "Oversized denim jacket",
        garmentVisibility: "Waist-up outfit visible",
        garmentColor: "Washed indigo",
        garmentFit: "Oversized",
        pose: "Leaning against a wall",
        handPosition: "Hands in pockets",
        composition: "Waist-up",
        lighting: "Hard editorial light",
        material: "Denim",
        styleDna: "Streetwear",
      },
    },
  ],
};
