import type { LockTemplate } from "../types.js";

export const peopleLockTemplate: LockTemplate = {
  categoryId: "people-portraits",
  categoryLabel: "People & Portraits",
  purpose:
    "Preserve person identity, pose, wardrobe presence, scene framing, and visual tone across model variants.",
  mandatoryLocks: [
    {
      key: "subject",
      label: "Subject",
      required: true,
      description: "Who the portrait is fundamentally about.",
      extractionHints: ["named profession", "role", "identity phrase", "hero subject wording"],
    },
    {
      key: "expression",
      label: "Expression",
      required: true,
      description: "The facial emotion or emotional read that defines the portrait.",
      extractionHints: ["smile", "serious", "confident", "calm", "dramatic", "intense"],
    },
    {
      key: "wardrobe",
      label: "Wardrobe",
      required: true,
      description: "Clothing or signature wearables that must remain recognizable.",
      extractionHints: ["hoodie", "saree", "kimono", "suit", "medical coat", "jewelry"],
    },
    {
      key: "background",
      label: "Background",
      required: true,
      description: "The supporting environment or backdrop that anchors the portrait.",
      extractionHints: ["brick wall", "office", "library cafe", "studio backdrop", "temple"],
    },
    {
      key: "composition",
      label: "Composition",
      required: true,
      description: "The framing logic that preserves how the subject is placed in the image.",
      extractionHints: ["close-up", "mid-shot", "full-body", "centered", "off-center"],
    },
    {
      key: "lighting",
      label: "Lighting",
      required: true,
      description: "The lighting setup or mood that materially defines the portrait.",
      extractionHints: ["window light", "golden hour", "hard key", "soft studio", "moody rain"],
      warning: "Lighting was not clearly extracted; portrait consistency may weaken.",
    },
    {
      key: "styleDna",
      label: "Style DNA",
      required: true,
      description: "The editorial or artistic language the image must preserve.",
      extractionHints: ["Vogue", "editorial", "cinematic", "watercolor", "punk beauty"],
      warning: "Style DNA was not clearly extracted; assembled output may drift across platforms.",
    },
  ],
  optionalLocks: [
    {
      key: "pose",
      label: "Pose",
      required: false,
      description: "Body position — only when stated (implicit in tight/medium portrait crops).",
      extractionHints: ["standing", "seated", "leaning", "three-quarter pose", "chest-up"],
    },
    {
      key: "gaze",
      label: "Gaze",
      required: false,
      description: "Where the subject is looking — only when eye direction is stated.",
      extractionHints: ["looking at camera", "sideways", "downward", "off-camera"],
    },
    {
      key: "handPosition",
      label: "Hand Position",
      required: false,
      description: "Visible hand behavior — only relevant when hands appear in frame.",
      extractionHints: ["hands on keyboard", "holding mug", "hands cupped", "arms crossed"],
    },
    {
      key: "headPosition",
      label: "Head Position",
      required: false,
      description: "Useful when the head tilt materially changes the portrait feel.",
    },
    {
      key: "crop",
      label: "Crop",
      required: false,
      description: "Useful when chest-up, close-up, full-body, or banner crop matters.",
    },
    {
      key: "cameraAngle",
      label: "Camera Angle",
      required: false,
      description: "Useful when eye-level, low-angle, or profile view is central to the prompt.",
    },
    {
      key: "material",
      label: "Material",
      required: false,
      description: "Useful when skin, fabric, or accessories need a specific physical read.",
    },
    {
      key: "surface",
      label: "Surface",
      required: false,
      description: "Useful when skin texture, pores, or painterly grain are explicit in the prompt.",
    },
    {
      key: "palette",
      label: "Palette",
      required: false,
      description: "Useful when color identity is central to the portrait.",
    },
  ],
  locksToAvoid: [
    "Exact eyelid percentages",
    "Face occupancy percentages",
    "Coordinate systems as a default portrait lock",
    "Catchlight clock positions",
    "Lens-height micrometrics unless absolutely necessary",
  ],
  extractionRules: [
    "Prefer explicit description-layer facts over inferred traits.",
    "Extract wardrobe only when the clothing is visible or identity-bearing.",
    "Treat hand position as required only when hands are visible or narratively important; otherwise use a stable fallback phrase during assembly.",
    "Map environment phrases like office, cafe, studio, temple, corridor, or brick wall into background.",
    "Separate expression from gaze; confident look and direct camera eye contact are not the same field.",
    "Treat editorial references, medium words, and visual genre cues as style DNA.",
  ],
  defaultNegativeLocks: [
    "No plastic skin.",
    "No distorted hands or fused fingers.",
    "No cropped extremities when hands are meant to remain visible.",
    "No warped facial proportions.",
    "No duplicate accessories or duplicated facial features.",
    "No generic wardrobe substitutions.",
    "No obvious AI artifacts or muddy texture.",
  ],
  examples: [
    {
      promptTitle: "Software Engineer Portrait",
      extracted: {
        subject: "Software engineer",
        expression: "Focused and quietly confident",
        gaze: "Looking toward camera or monitor with intent",
        pose: "Seated workstation portrait",
        handPosition: "Hands on keyboard",
        wardrobe: "Grey hoodie",
        background: "Tech workspace with brick wall",
        composition: "Chest-up environmental portrait",
        lighting: "Natural window light with soft office ambiance",
        styleDna: "Professional editorial workplace portrait",
      },
      notes: "This is the anchor example for the first MVP parser.",
    },
    {
      promptTitle: "Tech Founder Brick Wall Portrait",
      extracted: {
        subject: "Tech founder",
        expression: "Calm authority",
        gaze: "Direct eye contact",
        pose: "Standing or relaxed upright pose",
        wardrobe: "Founder-style casual-smart attire",
        background: "Brick wall backdrop",
        composition: "Mid-shot portrait",
        lighting: "Soft directional portrait light",
        styleDna: "Startup editorial portrait",
      },
    },
    {
      promptTitle: "Chef in Kitchen Portrait",
      extracted: {
        subject: "Chef",
        expression: "Warm confidence",
        gaze: "Camera-aware portrait gaze",
        pose: "Natural standing pose in working environment",
        handPosition: "One hand holding a kitchen object or resting naturally",
        wardrobe: "Chef uniform",
        background: "Kitchen environment",
        composition: "Environmental mid-shot portrait",
        lighting: "Soft practical kitchen light",
        styleDna: "Culinary editorial portrait",
      },
    },
  ],
};
