// ─── Narrative Video Formula Template ──────────────────────────────────────────
// Motion Formula v2.0 — character-driven shots. Holds the shared section
// builders reused across all video categories: the 15-section core structure
// (shot type through physics/motion dynamics) plus the 6-section Advanced
// Enhancement layer (visual detail through story telling) that's always
// assembled, never optional.

import { VideoCategory, VideoCategoryTemplate } from "../types.js"
import {
  MICRO_ACTION_BY_CATEGORY, QUALITY_TAG_BY_CATEGORY, AUDIO_BY_CATEGORY,
  ASPECT_RATIO_BY_CATEGORY, RENDER_ENGINE_BY_CATEGORY, MOOD_ATMOSPHERE_BY_CATEGORY,
  VISUAL_DETAIL_BY_CATEGORY, STORY_TELLING_BY_CATEGORY, CATEGORY_DEFAULTS,
} from "../dictionaries.js"

export const NARRATIVE_TEMPLATE: VideoCategoryTemplate = {
  name: "Narrative / Character",
  defaultCameraMove: "steadicam",
  defaultLighting: "practical interior",
  defaultDuration: "5-10s",
  sections: [
    "SHOT_TYPE", "SUBJECT", "ACTION_MICRO", "ENVIRONMENT", "LIGHTING_GEOMETRY",
    "CAMERA_MOVEMENT", "TIME_WEATHER", "STYLE", "QUALITY_TAG", "AUDIO",
    "ASPECT_RATIO", "DURATION", "COLOR_GRADE_RENDER", "MOOD_ATMOSPHERE", "PHYSICS_MOTION",
    "VISUAL_DETAIL", "CINEMATOGRAPHY", "REALISM", "SCENE_CONSISTENCY", "MOTION_QUALITY", "STORY_TELLING",
  ],
}

// Strips the "**LOCKS - X:** " label prefix off a lock sentence generated by
// lock-generator.ts, so its content can be folded under a v2.0 section label
// instead of the old end-of-prompt appendix convention.
function stripLockLabel(lockText: string): string {
  return lockText.replace(/^\*\*LOCKS - [A-Z]+:\*\*\s*/, "")
}

// ─── Core section builders (1-15, shared across all video categories) ────────

export function buildShotTypeSection(shotType: string): string {
  return `SHOT TYPE: ${shotType}`
}

export function buildSubjectSection(subject: string): string {
  return `SUBJECT: ${subject}`
}

export function buildActionSection(action: string, category: VideoCategory): string {
  const micro = MICRO_ACTION_BY_CATEGORY[category] ?? MICRO_ACTION_BY_CATEGORY.narrative
  return `ACTION & MICRO-ACTION: ${action} — ${micro}.`
}

export function buildEnvironmentSection(setting: string): string {
  return `ENVIRONMENT: ${setting}`
}

export function buildLightingGeometrySection(lighting: string): string {
  return `LIGHTING GEOMETRY: ${lighting}`
}

export function buildCameraMovementSection(cameraMove: string): string {
  return `CAMERA MOVEMENT: ${cameraMove}`
}

export function buildTimeWeatherSection(timeOfDay: string, weather: string): string {
  return `TIME & WEATHER: ${timeOfDay}; ${weather}.`
}

export function buildStyleSection(style: string): string {
  return `STYLE: ${style}`
}

export function buildQualityTagSection(category: VideoCategory): string {
  return `QUALITY TAG: ${QUALITY_TAG_BY_CATEGORY[category] ?? QUALITY_TAG_BY_CATEGORY.narrative}`
}

export function buildAudioSection(category: VideoCategory): string {
  return `AUDIO: ${AUDIO_BY_CATEGORY[category] ?? AUDIO_BY_CATEGORY.narrative}`
}

export function buildAspectRatioSection(category: VideoCategory): string {
  return `ASPECT RATIO: ${ASPECT_RATIO_BY_CATEGORY[category] ?? ASPECT_RATIO_BY_CATEGORY.narrative}`
}

export function buildDurationSection(category: VideoCategory): string {
  const d = CATEGORY_DEFAULTS[category] ?? CATEGORY_DEFAULTS.narrative
  return `DURATION: ${d.duration}`
}

export function buildColorGradeRenderSection(grade: string, category: VideoCategory): string {
  const render = RENDER_ENGINE_BY_CATEGORY[category] ?? RENDER_ENGINE_BY_CATEGORY.narrative
  return `COLOR GRADE & RENDER ENGINE: ${grade}. ${render}.`
}

export function buildMoodAtmosphereSection(category: VideoCategory): string {
  return `MOOD & EMOTIONAL ATMOSPHERE: ${MOOD_ATMOSPHERE_BY_CATEGORY[category] ?? MOOD_ATMOSPHERE_BY_CATEGORY.narrative}`
}

export function buildPhysicsMotionSection(motionLock: string): string {
  return `PHYSICS & MOTION DYNAMICS: ${stripLockLabel(motionLock)}`
}

// ─── Advanced Enhancement builders (16-21, always assembled) ─────────────────

export function buildVisualDetailSection(category: VideoCategory): string {
  return `VISUAL DETAIL: ${VISUAL_DETAIL_BY_CATEGORY[category] ?? VISUAL_DETAIL_BY_CATEGORY.narrative}`
}

export function buildCinematographySection(mood: string = "cinematic"): string {
  const refs: Record<string, string> = {
    "cinematic":   "CINEMATOGRAPHY: Roger Deakins — naturalistic motivated light. Emmanuel Lubezki — continuous immersive camera movement. Greig Fraser — high-contrast atmospheric depth",
    "documentary": "CINEMATOGRAPHY: handheld observational style, natural available light, unobtrusive camera presence, authentic unscripted feel",
    "commercial":  "CINEMATOGRAPHY: clean confident camera moves, glossy controlled lighting, brand-forward polish, high production value",
    "dreamlike":   "CINEMATOGRAPHY: Wong Kar-wai — saturated slow-motion intimacy. Terrence Malick — natural light, flowing camera, poetic pacing",
  }
  return refs[mood] ?? refs["cinematic"]
}

export function buildRealismSection(negatives: string[]): string {
  return `REALISM: ${negatives.join(" | ")}`
}

export function buildSceneConsistencySection(continuityLock: string): string {
  return `SCENE CONSISTENCY: ${stripLockLabel(continuityLock)}`
}

export function buildMotionQualitySection(cameraLock: string, temporalLock: string): string {
  return `MOTION QUALITY: ${stripLockLabel(cameraLock)} ${stripLockLabel(temporalLock)}`
}

export function buildStoryTellingSection(category: VideoCategory): string {
  return `STORY TELLING: ${STORY_TELLING_BY_CATEGORY[category] ?? STORY_TELLING_BY_CATEGORY.narrative}`
}

// ─── LOCK generators (Motion Formula v2.0, narrative category) ───────────────
// Video diffusion drifts over time, not within one frame — these four raw
// lock sentences feed PHYSICS & MOTION DYNAMICS, MOTION QUALITY, and SCENE
// CONSISTENCY above. Kept as their own dispatchable functions (rather than
// inlined) because lock-generator.ts swaps in a category-specific
// implementation of all four for product/nature/action/abstract.

export function buildMotionLock(motionSpeed: string, motionDirection: string): string {
  return `**LOCKS - MOTION:** subject moves at a ${motionSpeed}, travelling ${motionDirection}, constant speed maintained throughout — no unexplained acceleration, deceleration, or teleporting between frames.`
}

export function buildCameraLock(cameraMoveType: string, cameraStart: string, cameraEnd: string): string {
  return `**LOCKS - CAMERA:** single continuous ${cameraMoveType} move, starting on ${cameraStart} and ending on ${cameraEnd} — no cuts, no additional moves layered on top, no drift off the described path.`
}

export function buildTemporalLock(beginState: string, endState: string): string {
  return `**LOCKS - TEMPORAL:** clip begins with ${beginState} and ends with ${endState} — the action must resolve within the clip's duration, no abrupt mid-action cutoff, no looping back to the start state.`
}

export function buildContinuityLock(identityAnchor: string): string {
  return `**LOCKS - CONTINUITY:** ${identityAnchor} remains visually identical in every frame — same face, hairstyle, wardrobe, and proportions from first frame to last. No identity drift, no morphing, no wardrobe changes mid-clip.`
}
